version: '3'

services:
    etl:
        image: d3b-warehouse-etl:latest
        build: .
        env_file: compose.env
        depends_on: 
            - staging
        command: ["./wait-for-db.sh", "./run.sh"]
    staging:
        image: postgres:9.6
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        ports:
            - 5432:5432   
    metabase:
        image: metabase/metabase:latest
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_HOST=staging 
            - MB_DB_PORT=5432
            - MB_DB_DBNAME=postgres
            - MB_DB_USER=postgres
        ports:
            - 3000:3000
        depends_on:
            - staging 
            - etl
